export type UIState =
  | 'default'
  | 'hover'
  | 'pressed'
  | 'focused'
  | 'disabled'
  | 'loading'
  | 'selected'
  | 'active'
  | 'inactive'
  | 'success'
  | 'pending'
  | 'error'
  | 'warning'

export type Size = 'sm' | 'md' | 'lg'
